### PR TITLE
Return react-native-codegen to devDependencies

### PR DESCRIPTION
**Pull request by svbutko**
Fixes: https://github.com/react-native-community/rn-diff-purge/issues/50

### CODE REVIEW

**Comment by mikehardy** [comment]
Obviously you have direct experience with this (I saw your comments showing the error - I believe you!), just wierdly it worked for me to remove react-native-codegen. That said, including it also works. Strange one!

**Comment by svbutko** [comment]
My fault, somehow `package-lock` generated it first time incorrectly, removed `package-lock` and it was added

**Comment by mikehardy** [comment]
Whew! :sweat_smile: I could swear that in a clean build (CI style, no node_modules / Pods existing) it worked for me - just spun up a VM real quickly to verify and it does look good for me too still :+1: :smile:

**Comment by Adnan-Bacic** [comment]
so react-native-codegen has to be removed? i assumed it was an error so i was searching for someone else who noticed, before i just removed it, and i ended here.

it was just added in rn 0.65:

https://reactnative.dev/blog/2021/08/17/version-065#notable-dependency-version-updates-and-gotchas

> react-native-codegen version 0.0.7 is now needed as a devDependency in the package.json

so it seems weird to remove it the very next version, just 2 months later

**Pull request closed without merging**
