### PR TITLE
chore: rename links to react-native-community

### PR DESCRIPTION
**Pull request by thymikee**
Linking to `react-native-community` now that we're migrated. cc @pvinis

### CODE REVIEW

**Comment by pvinis** [comment]
I think the readme changes are done in #2. Sorry for that, I saw it first this morning. I can fix and merge this. Thanks.

**Comment by pvinis** [comment]
Forget my previous comment :D

**Comment by thymikee** [comment]
Yup! Looks like there are only spacing changes now :D

**Comment by pvinis** [comment]
Aren't the spaces required to make the new line?

**Comment by thymikee** [comment]
Oh, if that's what you want to achieve then they should be just newlines – markdown should not have any trailing whitespace (e.g. Prettier strips it). I'll close it then, as there's no real value in this PR :)

**Comment by pvinis** [comment]
I am rewriting parts of the text, so I think I will make sure to remove the trailing spaces and convert the lines to lists.

**Pull request closed without merging**
